const fs=require('fs');
const file='portfolio/dist/index.html';let h=fs.readFileSync(file,'utf8');
h=h.replace(/<meta name="description"[^>]+>/,'<meta name="description" content="Moaaz Mohamed — Python, data processing, backend systems and cloud infrastructure. Explore projects and get in touch about your next build.">');
h=h.replace('</head>',`<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2303080e'/%3E%3Ctext x='32' y='43' text-anchor='middle' font-family='sans-serif' font-size='34' fill='%238fd6e8'%3EM%3C/text%3E%3C/svg%3E">
<style>
:root{--cyan-dim:#91b5c5}.hero{min-height:90vh}.hero-role{max-width:40ch}.hero-label{color:var(--amber);font-family:var(--font-mono);font-size:14px;letter-spacing:2px;margin-bottom:22px;text-transform:uppercase}.profile-frame{max-width:350px;border-radius:100px 16px 16px 16px;padding:0}.profile-img{height:440px;object-fit:cover;object-position:50% 40%;border-radius:0;clip-path:inset(0 0 0 3%);transform:scale(1.06)}.profile-frame:hover .profile-img{transform:scale(1.06)}.photo-caption{font-family:var(--font-mono);font-size:14px;color:var(--cyan-dim);margin-top:18px;text-align:center}.hero-visual{flex-direction:column;align-items:center}.fade-in-up{opacity:1;transform:none}.project-panel{grid-template-columns:110px 1fr}.project-visual{font-family:var(--font-mono);font-size:32px;color:var(--cyan);padding:24px}.project-link{color:var(--amber);display:inline-block;margin-top:24px;font-weight:600}.tag{font-size:14px}.contact-links{grid-template-columns:1fr 1fr}.contact-link-value{overflow-wrap:anywhere}.section{padding:85px 0}.skip{position:absolute;left:20px;top:-100px;z-index:100;background:var(--amber);color:#03080e;padding:12px}.skip:focus{top:15px}:focus-visible{outline:2px solid var(--amber);outline-offset:5px}.footer-note{text-align:center;color:var(--cyan-dim);font-size:14px}.nav-links{display:flex;gap:24px}.mouse-glow{display:none}
@media(max-width:780px){.hero-inner{gap:42px;padding:50px 24px}.hero{padding-top:110px}.hero-name{font-size:clamp(2.8rem,10vw,4rem)}.nav-inner{height:auto;min-height:90px;flex-direction:column;justify-content:center;gap:12px;padding:14px}.nav-links{display:flex;gap:20px;font-size:14px}.container{padding-left:24px;padding-right:24px}.profile-frame{max-width:300px}.profile-img{height:360px}.project-panel{grid-template-columns:1fr}.project-visual{justify-content:flex-start;padding:16px 28px}.project-content{padding:28px}.contact-links{grid-template-columns:1fr}.section{scroll-margin-top:110px}.section h2{font-size:2rem}.hero-cta{gap:12px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation:none!important;transition:none!important}.project-panel{transform:none!important}}
</style></head>`);
h=h.replace('<body>','<body><a class="skip" href="#about">Skip to content</a>');
h=h.replace('<a href="#experience">Experience</a>','<a href="#expertise">Expertise</a>');
h=h.replace('<h1 class="hero-name">','<p class="hero-label">Data · Cloud · Backend</p><h1 class="hero-name">');
h=h.replace('Computer &amp; Communication Engineering student building systems that process, route, and transform data.','I build practical systems that turn raw data into clear, usable information.');
h=h.replaceAll('es.moaz.mostafa2024@alexu.edu.eg','moaazmoh@icloud.com').replace('Email Moaaz','Let’s talk about your project');
h=h.replace('6bb1eef5-23bd-4f65-8852-167197a82924.png','portrait.png');
h=h.replace(/<div class="about-text">[\s\S]*?<\/div>\s*<div class="about-stats">[\s\S]*?<\/div>\s*<\/div>\s*<div class="about-stat-card">[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/,`<div class="about-text"><p>I’m Moaaz, a developer focused on data engineering, backend systems, and cloud infrastructure. I work with Python, SQL, and C to organize information, automate processing, and build useful software.</p><p>My approach is straightforward: understand the problem, build a clear solution, and keep the code maintainable. Explore my projects below to see how I put that into practice.</p></div><div class="about-stats"><div class="about-stat-card"><div class="about-stat-num">Data with purpose</div><div class="about-stat-label">Cleaning, transformation &amp; analysis</div></div><div class="about-stat-card"><div class="about-stat-num">Systems that fit</div><div class="about-stat-label">Backend logic &amp; cloud infrastructure</div></div></div>`);
h=h.replace(/<section id="experience"[\s\S]*?<\/section>/,`<section id="expertise" class="section"><div class="container"><h2>What I work on</h2><div class="timeline"><div class="timeline-item"><h3>Data processing &amp; analysis</h3><p class="timeline-org">Python · SQL · Pandas</p><p>Cleaning datasets, transforming raw records, and exploring data to make it easier to use.</p></div><div class="timeline-item"><h3>Backend &amp; application logic</h3><p class="timeline-org">Python · C · Git · Docker</p><p>Structured applications with clear workflows for managing records and processing transactions.</p></div><div class="timeline-item"><h3>Cloud infrastructure</h3><p class="timeline-org">AWS · Networking · Storage</p><p>Configuring cloud resources, networks, and storage with attention to organization and access.</p></div></div></div></section>`);
const projects=[['Supermarket Data Analysis','Python · Data analysis','Data cleaning and analysis with Pandas, using a supermarket dataset in a Jupyter notebook.','DEPI',['Python','Pandas','Jupyter']],['Library & Hospital Management','Python · Application development','Python management systems that model library and hospital workflows. Explore the implementation and application logic in the repository.','task2',['Python','Management systems']],['Bank Management System','C · Systems programming','A banking application covering account management, transactions, and file-based data storage. This repository is a fork of the shared bank-system project.','Final-project',['C','File I/O','Data structures']]];
h=h.replace(/<div class="project-grid">[\s\S]*?<\/section>/,`<div class="project-grid">${projects.map((p,i)=>`<article class="project-panel"><div class="project-visual" aria-hidden="true">0${i+1}</div><div class="project-content"><div class="project-header"><h3>${p[0]}</h3></div><p class="project-role">${p[1]}</p><p class="project-desc">${p[2]}</p><div class="tag-row">${p[4].map(t=>`<span class="tag">${t}</span>`).join('')}</div><a class="project-link" href="https://github.com/moaaz-z/${p[3]}" target="_blank" rel="noopener noreferrer">View repository <span aria-hidden="true">↗</span><span class="sr-only"></span></a></div></article>`).join('')}</div></div></section>`);
h=h.replace("Let's Connect","Let’s build something useful.").replace('Open to data engineering, cloud, and systems opportunities.','Have a data or software project in mind? Tell me what you need, and let’s discuss how I can help.');
h=h.replace(/<a href="tel:[\s\S]*?<\/a>/,'');
h=h.replace('<a href="#" class="contact-link">','<a href="https://github.com/moaaz-z" class="contact-link" target="_blank" rel="noopener noreferrer">').replace('>LinkedIn<','>GitHub<').replace('<span class="contact-link-value">Moaaz Mohamed</span>','<span class="contact-link-value">moaaz-z ↗</span>');
h=h.replace('</footer>','<p class="footer-note">Moaaz Mohamed · Data, cloud &amp; backend development</p></footer>');
h=h.replace(/<script>[\s\S]*?<\/script>/,'');fs.writeFileSync(file,h);
